71 implement admin repository
TovahParnes/BirdAI_D7057E pull request #156
Opened 2023-10-30 10:34 UTC by TovahParnes

2023-10-30 11:44 UTC, 99jessve requested changes

2023-10-30 11:44 UTC, 99jessve commented on src/internal/controllers/admins_controller.go
> +	return utils.Response(nil)
Denna borde kanske tas bort? Förstår att den är nice för testning men borde inte ta bort alla admins varje gång vi startar upp backenden

2023-10-30 11:44 UTC, 99jessve commented on src/internal/handlers/routes_handler.go
> +	handler.controller.ResetAdmin()
Ta bort denna rad.

2023-10-30 11:44 UTC, 99jessve commented on src/internal/controllers/admins_controller.go
> +	}
Tror det ska vara AdminDB den ska kolla efter, nu kan man sätta samma access på samma person flera gånger.
```suggestion
	if utils.IsType(currentAdmin, models.AdminDB{}) {
		return utils.ErrorToResponse(http.StatusConflict, "Admin already exists", "Admin with that user id already exists")
	}
```

![image](https://github.com/TovahParnes/BirdAI_D7057E/assets/21337949/5799514e-486e-4ed3-bde6-14952426aba3)

2023-10-30 13:02 UTC, lindstromemil commented on src/internal/controllers/access_controller.go
> +	if utils.IsType(response, models.AdminOutput{}) && response.Data.(*models.AdminOutput).Access == "superadmin"{
När jag testade i Swagger så kunde den inte hitta att min user var superadmin utan att jag ändrade denna raden till att ha pointers i denna check. Det är funktionen CIsSuperAdmin i access_controller.go

```suggestion
	if utils.IsType(response, &models.AdminOutput{}) && response.Data.(*models.AdminOutput).Access == "superadmin"{
```

2023-10-30 13:04 UTC, lindstromemil commented on src/internal/handlers/routes_handler.go
> +	handler.controller.ResetAdmin()
Vi bör väl inte ta bort alla admins varje gång vi startar programmet?
```suggestion
```

2023-10-30 13:08 UTC, lindstromemil commented on src/internal/controllers/admins_controller.go
> +	}
Just nu går det att gör samma person till admin flera gånger. Skulle tro att det är checken som inte blir rätt gjord för stunden. Ska sätta mig och testa göra om den också

![image](https://github.com/TovahParnes/BirdAI_D7057E/assets/60612941/91ae973d-663c-47b1-8b0e-b7bb8b2b6097)

2023-10-30 13:23 UTC, lindstromemil commented on src/internal/controllers/admins_controller.go
> +	}
Jag uppdaterade checken i CCreateAdmin till att kolla efter *models.adminDB{} istället och nu gav den error 
```suggestion
func (c *Controller) CCreateAdmin(adminInput *models.AdminInput) (models.Response) {
	currentAdmin := c.db.Admin.GetAdminByUserId(adminInput.UserId)
	if utils.IsTypeError(currentAdmin) && currentAdmin.Data.(models.Err).StatusCode != http.StatusNotFound{
		return currentAdmin
	}
	if utils.IsType(currentAdmin, &models.AdminDB{}) {
		return utils.ErrorToResponse(http.StatusConflict, "Admin already exists", "Admin with that user id already exists")
	}
```
Då fick jag detta istället
![image](https://github.com/TovahParnes/BirdAI_D7057E/assets/60612941/4dc74039-e62b-43c1-9703-8b3f3584e55e)

2023-10-30 16:10 UTC, TovahParnes commented on src/internal/controllers/access_controller.go
> +	if utils.IsType(response, models.AdminOutput{}) && response.Data.(*models.AdminOutput).Access == "superadmin"{
Det fungerar för mig utan &, jag la till i utils.IsType att ge true om det är rätt modell eller pointer för rätt modell.

2023-10-30 16:13 UTC, TovahParnes commented on src/internal/controllers/admins_controller.go
> +	}
Done

2023-10-31 07:06 UTC, 99jessve approved these changes
Tyckte typ om den där FirstAdmin metoden som kallas i login men kan ha admins/me endpointen tills vidare

2023-10-31 10:25 UTC, lindstromemil approved these changes

2023-11-01 09:08 UTC, merged