257 final fixes frontend
TovahParnes/BirdAI_D7057E pull request #258
Opened 2023-12-04 13:02 UTC by fabianwidell

2023-12-04 13:55 UTC, filber-9 requested changes
Bra namngivning, lätt att följa. Finns bara lite död kod och logs med

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/library/library.component.ts
> +    this.changePage(0);
behövs denna?

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/library/library.component.ts
> +          console.log("inuti")
log

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/library/library.component.ts
> +        console.log("hejsan")
log

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/library/library.component.ts
> +        console.log("det var ett error")
log

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/services/auth-guard.service.ts
> +    console.log(authKey);
log

2023-12-04 13:55 UTC, filber-9 commented on src/frontend/src/app/services/auth-guard.service.ts
> +      console.log(state.url);
log

2023-12-05 11:42 UTC, fabianwidell commented on src/frontend/src/app/library/library.component.ts
> +    this.changePage(0);
ja den behövs, utan så refreshas inte sidan när kommer tillbaka från species

2023-12-05 13:46 UTC, merged