46 Implement endpoints for frontend
TovahParnes/BirdAI_D7057E pull request #47
Opened 2023-09-28 09:43 UTC by 99jessve

2023-09-28 09:54 UTC, TovahParnes commented
GetUserById, DeleteUser och ParchUser ger error i swagger. DeleteUser och PatchUser ger också error att path variabeln id måste vara en int.
```
Failed to fetch.
Possible Reasons:

CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
```

2023-09-28 09:55 UTC, TovahParnes requested changes
GetUserById, DeleteUser och ParchUser ger error i swagger. DeleteUser och PatchUser ger också error att path variabeln id måste vara en int.

Failed to fetch.
Possible Reasons:
```
CORS
Network Failure
URL scheme must be "http" or "https" for CORS request.
```

2023-09-28 11:50 UTC, 99jessve commented
Har implementerat delete, update och me nu som inte fanns med. Dock funkar getbyid för mig så kan kika sen varför det inte funkar 👍

2023-09-28 12:01 UTC, 99jessve commented
Verkar funka för Emil så kanske är något knas

2023-09-29 11:22 UTC, TovahParnes approved these changes
Nu fungerar swagger

2023-09-29 12:06 UTC, merged